version: '2'
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./volumes/nginx/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "/var/www/cofacts:/var/www/cofacts:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "/var/log:/var/log"
    restart: always

  site:
    image: mrorz/rumors-site
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - SERVER_ROLLBAR_SERVER_TOKEN=CHANGE_ME
      - SERVER_ROLLBAR_ENV=production
      - PUBLIC_API_URL=https://cofacts-api.g0v.tw
      - PUBLIC_APP_ID=RUMORS_SITE
      - PUBLIC_GA_TRACKER=UA-98468513-1

    restart: always

  site-staging:
    image: mrorz/rumors-site:staging
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - SERVER_ROLLBAR_SERVER_TOKEN=CHANGE_ME
      - SERVER_ROLLBAR_ENV=staging
      - PUBLIC_API_URL=https://cofacts-api.hacktabl.org
      - PUBLIC_APP_ID=RUMORS_SITE
      - PUBLIC_GA_TRACKER=UA-98468513-5
    restart: always

  api:
    image: mrorz/rumors-api
    environment:
      - ELASTICSEARCH_URL=http://db:9200
      - ELASTIC_LOG_LEVEL=info
      - PORT=5000,
      - COOKIE_SECRETS=
      - ROLLBAR_TOKEN=CHANGE_ME
      - ROLLBAR_ENV=production
      - RUMORS_SITE_CORS_ORIGIN=https://cofacts.g0v.tw
      - RUMORS_LINE_BOT_SECRET=CHANGE_ME
      - FACEBOOK_APP_ID=CHANGE_ME
      - FACEBOOK_SECRET=CHANGE_ME
      - FACEBOOK_CALLBACK_URL=CHANGE_ME
      - TWITTER_CONSUMER_KEY=CHANGE_ME
      - TWITTER_CONSUMER_SECRET=CHANGE_ME
      - TWITTER_CALLBACK_URL=CHANGE_ME
      - GITHUB_CLIENT_ID=CHANGE_ME
      - GITHUB_SECRET=CHANGE_ME
      - GITHUB_CALLBACK_URL=CHANGE_ME
      - URL_RESOLVER_URL=http://url-resolver:4000

    restart: always

  api-staging:
    image: mrorz/rumors-api:staging
    environment:
      - ELASTICSEARCH_URL=http://db-staging:9200
      - ELASTIC_LOG_LEVEL=info
      - PORT=5000,
      - COOKIE_SECRETS=
      - ROLLBAR_TOKEN=CHANGE_ME
      - ROLLBAR_ENV=staging
      - RUMORS_SITE_CORS_ORIGIN=https://cofacts.hacktabl.org
      - RUMORS_LINE_BOT_SECRET=CHANGE_ME
      - FACEBOOK_APP_ID=CHANGE_ME
      - FACEBOOK_SECRET=CHANGE_ME
      - FACEBOOK_CALLBACK_URL=CHANGE_ME
      - TWITTER_CONSUMER_KEY=CHANGE_ME
      - TWITTER_CONSUMER_SECRET=CHANGE_ME
      - TWITTER_CALLBACK_URL=CHANGE_ME
      - GITHUB_CLIENT_ID=CHANGE_ME
      - GITHUB_SECRET=CHANGE_ME
      - GITHUB_CALLBACK_URL=CHANGE_ME
      - URL_RESOLVER_URL=http://url-resolver:4000
    restart: always

  db:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    environment:
      - "path.repo=/usr/share/elasticsearch/data"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - "./volumes/db-production:/usr/share/elasticsearch/data"
    restart: always
    # No exposed ports by default.
    # When migration, manually edit docker-compose to add "ports"
    # and do `docker-compose restart db`.

  db-staging:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    environment:
      - "path.repo=/usr/share/elasticsearch/data"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - "./volumes/db-staging:/usr/share/elasticsearch/data"
    restart: always
    ports: # expose ports for db migration operations
      - "62222:9200"

  url-resolver:
    image: johnsonliang/cofacts-url-resolver
    mem_limit: 250m
    restart: always
    ports: # expose for debugging
      - "4000:4000"
    environment:
      - YOUTUBE_API_KEY=CHANGE_ME
